const foods = [
  { name: "Egg", category: "protein", portion: "1 egg", kcal: 78, protein_g: 6.3, fat_g: 5.3, fat_type: "mixed", carbs_g: 0.6, cholesterol_mg: 186, collagen_g: 1, vitaminC_mg: 0, calcium_mg: 25 },
  { name: "Milk (whole)", category: "dairy", portion: "1 cup (240ml)", kcal: 146, protein_g: 7.7, fat_g: 7.9, fat_type: "mixed", carbs_g: 11.5, cholesterol_mg: 34, collagen_g: 0, vitaminC_mg: 0, calcium_mg: 271 },
  { name: "Butter", category: "fat", portion: "1 tbsp (14g)", kcal: 100, protein_g: 0.1, fat_g: 11.3, fat_type: "unhealthy", carbs_g: 0.01, cholesterol_mg: 30, collagen_g: 0, vitaminC_mg: 0, calcium_mg: 3 },
  { name: "Olive oil", category: "fat", portion: "1 tbsp (15ml)", kcal: 132, protein_g: 0, fat_g: 15, fat_type: "healthy", carbs_g: 0, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 0, calcium_mg: 0.2 },
  { name: "Chicken breast", category: "protein", portion: "1 breast", kcal: 248, protein_g: 46.5, fat_g: 5.4, fat_type: "healthy", carbs_g: 0, cholesterol_mg: 128, collagen_g: 3, vitaminC_mg: 0, calcium_mg: 23 },
  { name: "Ground beef", category: "protein", portion: "1 patty", kcal: 213, protein_g: 22.1, fat_g: 12.8, fat_type: "mixed", carbs_g: 0, cholesterol_mg: 75, collagen_g: 1.7, vitaminC_mg: 0, calcium_mg: 15 },
  { name: "Pork chop", category: "protein", portion: "1 chop", kcal: 206, protein_g: 23, fat_g: 11.9, fat_type: "mixed", carbs_g: 0, cholesterol_mg: 68, collagen_g: 1.7, vitaminC_mg: 0, calcium_mg: 16 },
  { name: "Salmon fillet", category: "protein", portion: "1 fillet", kcal: 250, protein_g: 24, fat_g: 15.6, fat_type: "healthy", carbs_g: 0, cholesterol_mg: 66, collagen_g: 3.6, vitaminC_mg: 0, calcium_mg: 11 },
  { name: "Shrimp", category: "protein", portion: "6 large shrimp", kcal: 84, protein_g: 20.4, fat_g: 0.3, fat_type: "healthy", carbs_g: 0.2, cholesterol_mg: 166, collagen_g: 2.6, vitaminC_mg: 0, calcium_mg: 60 },
  { name: "Tofu block", category: "protein", portion: "1/2 cup cubed", kcal: 91, protein_g: 9.6, fat_g: 4.8, fat_type: "healthy", carbs_g: 2.4, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 0, calcium_mg: 420 },
  { name: "Rice (cooked)", category: "grain", portion: "1/2 cup", kcal: 101, protein_g: 2.1, fat_g: 0.2, fat_type: "healthy", carbs_g: 22, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 0, calcium_mg: 8 },
  { name: "Pasta (cooked)", category: "grain", portion: "1/2 cup", kcal: 110, protein_g: 4.1, fat_g: 0.6, fat_type: "healthy", carbs_g: 21, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 0, calcium_mg: 7 },
  { name: "Bread slice", category: "grain", portion: "1 slice", kcal: 67, protein_g: 2.3, fat_g: 0.8, fat_type: "mixed", carbs_g: 12, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 0, calcium_mg: 60 },
  { name: "Potato", category: "carbs", portion: "1 potato", kcal: 110, protein_g: 2.9, fat_g: 0.1, fat_type: "healthy", carbs_g: 26, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 20, calcium_mg: 10 },
  { name: "Carrot", category: "vegetable", portion: "1 carrot", kcal: 25, protein_g: 0.6, fat_g: 0.1, fat_type: "healthy", carbs_g: 6, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 3, calcium_mg: 20 },
  { name: "Broccoli", category: "vegetable", portion: "1 broccoli crown", kcal: 55, protein_g: 5.1, fat_g: 0.6, fat_type: "healthy", carbs_g: 11, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 148, calcium_mg: 78 },
  { name: "Spinach bunch", category: "vegetable", portion: "1 bunch (340g)", kcal: 78, protein_g: 9.9, fat_g: 1.4, fat_type: "healthy", carbs_g: 12.2, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 95, calcium_mg: 337 },
  { name: "Tomato", category: "vegetable", portion: "1 tomato", kcal: 22, protein_g: 1, fat_g: 0.2, fat_type: "healthy", carbs_g: 4.8, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 17, calcium_mg: 12 },
  { name: "Onion", category: "vegetable", portion: "1 onion", kcal: 44, protein_g: 1.2, fat_g: 0.1, fat_type: "healthy", carbs_g: 10, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 7, calcium_mg: 25 },
  { name: "Garlic clove", category: "vegetable", portion: "1 clove", kcal: 5, protein_g: 0.2, fat_g: 0.02, fat_type: "healthy", carbs_g: 1, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 1, calcium_mg: 2 },
  { name: "Lettuce head", category: "vegetable", portion: "1 head (539g)", kcal: 81, protein_g: 7.6, fat_g: 1.1, fat_type: "healthy", carbs_g: 15.6, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 48, calcium_mg: 194 },
  { name: "Cucumber", category: "vegetable", portion: "1 cucumber", kcal: 30, protein_g: 1.4, fat_g: 0.1, fat_type: "healthy", carbs_g: 6, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 5, calcium_mg: 16 },
  { name: "Apple", category: "fruit", portion: "1 apple", kcal: 95, protein_g: 0.5, fat_g: 0.3, fat_type: "healthy", carbs_g: 25, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 8, calcium_mg: 11 },
  { name: "Banana", category: "fruit", portion: "1 banana", kcal: 105, protein_g: 1.3, fat_g: 0.4, fat_type: "healthy", carbs_g: 27, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 9, calcium_mg: 5 },
  { name: "Cheese slice", category: "dairy", portion: "1 slice", kcal: 113, protein_g: 7, fat_g: 9.2, fat_type: "unhealthy", carbs_g: 0.4, cholesterol_mg: 29, collagen_g: 0, vitaminC_mg: 0, calcium_mg: 202 },
  { name: "Mayonnaise", category: "fat", portion: "1 tbsp (14g)", kcal: 99, protein_g: 0.1, fat_g: 11, fat_type: "unhealthy", carbs_g: 0.1, cholesterol_mg: 7, collagen_g: 0, vitaminC_mg: 0, calcium_mg: 2 },
  { name: "Ketchup", category: "vegetable", portion: "1 tbsp (17g)", kcal: 16, protein_g: 0.4, fat_g: 0.1, fat_type: "healthy", carbs_g: 4, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 2, calcium_mg: 4 },
  { name: "Frank's Hot Sauce", category: "vegetable", portion: "1 tsp (5ml)", kcal: 3, protein_g: 0.1, fat_g: 0, fat_type: "healthy", carbs_g: 0.5, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 1, calcium_mg: 1 }
];
