const foods = [
  { name: "Egg", category: "protein", portion: "1 medium (50g)", kcal: 78, protein_g: 6.3, fat_g: 5.3, fat_type: "mixed", carbs_g: 0.6, cholesterol_mg: 186, collagen_g: 1, vitaminC_mg: 0, calcium_mg: 25 },
  { name: "Milk (whole)", category: "dairy", portion: "100g (≈100ml)", kcal: 61, protein_g: 3.2, fat_g: 3.3, fat_type: "mixed", carbs_g: 4.8, cholesterol_mg: 14, collagen_g: 0, vitaminC_mg: 0, calcium_mg: 113 },
  { name: "Butter", category: "fat", portion: "100g", kcal: 717, protein_g: 0.9, fat_g: 81, fat_type: "unhealthy", carbs_g: 0.1, cholesterol_mg: 215, collagen_g: 0, vitaminC_mg: 0, calcium_mg: 24 },
  { name: "Olive oil", category: "fat", portion: "100g", kcal: 884, protein_g: 0, fat_g: 100, fat_type: "healthy", carbs_g: 0, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 0, calcium_mg: 1 },
  { name: "Chicken breast", category: "protein", portion: "100g (cooked)", kcal: 165, protein_g: 31, fat_g: 3.6, fat_type: "healthy", carbs_g: 0, cholesterol_mg: 85, collagen_g: 2, vitaminC_mg: 0, calcium_mg: 15 },
  { name: "Ground beef (10% fat)", category: "protein", portion: "100g (cooked)", kcal: 250, protein_g: 26, fat_g: 15, fat_type: "mixed", carbs_g: 0, cholesterol_mg: 88, collagen_g: 2, vitaminC_mg: 0, calcium_mg: 18 },
  { name: "Pork loin", category: "protein", portion: "100g", kcal: 242, protein_g: 27, fat_g: 14, fat_type: "mixed", carbs_g: 0, cholesterol_mg: 80, collagen_g: 2, vitaminC_mg: 0, calcium_mg: 19 },
  { name: "Salmon", category: "protein", portion: "100g", kcal: 208, protein_g: 20, fat_g: 13, fat_type: "healthy", carbs_g: 0, cholesterol_mg: 55, collagen_g: 3, vitaminC_mg: 0, calcium_mg: 9 },
  { name: "Shrimp", category: "protein", portion: "100g", kcal: 99, protein_g: 24, fat_g: 0.3, fat_type: "healthy", carbs_g: 0.2, cholesterol_mg: 195, collagen_g: 3, vitaminC_mg: 0, calcium_mg: 70 },
  { name: "Tofu", category: "protein", portion: "100g", kcal: 76, protein_g: 8, fat_g: 4, fat_type: "healthy", carbs_g: 2, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 0, calcium_mg: 350 },
  { name: "White rice (cooked)", category: "grain", portion: "100g", kcal: 130, protein_g: 2.7, fat_g: 0.3, fat_type: "healthy", carbs_g: 28, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 0, calcium_mg: 10 },
  { name: "Pasta (cooked)", category: "grain", portion: "100g", kcal: 157, protein_g: 5.8, fat_g: 0.9, fat_type: "healthy", carbs_g: 30, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 0, calcium_mg: 10 },
  { name: "Bread (white)", category: "grain", portion: "1 slice (25g)", kcal: 67, protein_g: 2.3, fat_g: 0.8, fat_type: "mixed", carbs_g: 12, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 0, calcium_mg: 60 },
  { name: "Potato", category: "starch", portion: "1 medium (150g)", kcal: 110, protein_g: 2.9, fat_g: 0.1, fat_type: "healthy", carbs_g: 26, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 20, calcium_mg: 10 },
  { name: "Carrot", category: "vegetable", portion: "1 medium (60g)", kcal: 25, protein_g: 0.6, fat_g: 0.1, fat_type: "healthy", carbs_g: 6, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 3, calcium_mg: 20 },
  { name: "Broccoli", category: "vegetable", portion: "100g", kcal: 34, protein_g: 2.8, fat_g: 0.4, fat_type: "healthy", carbs_g: 7, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 89, calcium_mg: 47 },
  { name: "Spinach", category: "vegetable", portion: "100g", kcal: 23, protein_g: 2.9, fat_g: 0.4, fat_type: "healthy", carbs_g: 3.6, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 28, calcium_mg: 99 },
  { name: "Tomato", category: "vegetable", portion: "1 medium (120g)", kcal: 22, protein_g: 1, fat_g: 0.2, fat_type: "healthy", carbs_g: 4.8, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 17, calcium_mg: 12 },
  { name: "Onion", category: "vegetable", portion: "1 medium (110g)", kcal: 44, protein_g: 1.2, fat_g: 0.1, fat_type: "healthy", carbs_g: 10, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 7, calcium_mg: 25 },
  { name: "Garlic", category: "vegetable", portion: "1 clove (3g)", kcal: 5, protein_g: 0.2, fat_g: 0.02, fat_type: "healthy", carbs_g: 1, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 1, calcium_mg: 2 },
  { name: "Lettuce", category: "vegetable", portion: "100g", kcal: 15, protein_g: 1.4, fat_g: 0.2, fat_type: "healthy", carbs_g: 2.9, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 9, calcium_mg: 36 },
  { name: "Cucumber", category: "vegetable", portion: "1 medium (200g)", kcal: 30, protein_g: 1.4, fat_g: 0.1, fat_type: "healthy", carbs_g: 6, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 5, calcium_mg: 16 },
  { name: "Apple", category: "fruit", portion: "1 medium (182g)", kcal: 95, protein_g: 0.5, fat_g: 0.3, fat_type: "healthy", carbs_g: 25, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 8, calcium_mg: 11 },
  { name: "Banana", category: "fruit", portion: "1 medium (118g)", kcal: 105, protein_g: 1.3, fat_g: 0.4, fat_type: "healthy", carbs_g: 27, cholesterol_mg: 0, collagen_g: 0, vitaminC_mg: 9, calcium_mg: 5 },
  { name: "Cheddar cheese", category: "dairy", portion: "100g", kcal: 402, protein_g: 25, fat_g: 33, fat_type: "unhealthy", carbs_g: 1.3, cholesterol_mg: 105, collagen_g: 0, vitaminC_mg: 0, calcium_mg: 721 }
];
